### ISSUE TITLE
OpenWRT ZSUN Piratebox

### ISSUE THREAD

**Issue by mstrmnn** [TheExpertNoob/scripts#3]
Dear TheExpertNoob,

I followed your tutorial to get Piratebox on a ZSUN.
Installing OpenWRT was easy.
Problems started with: <opkg update && opkg install -d ram e2fsprogs dosfstools fdisk>
Error line: <opkg_install_cmd: Cannot install package dosfstools.>
I tried to install "dosfstools_4.0-2_mipsel_24kc.ipk" manually but this failed, too.
Error code: <pkg_hash_fetch_best_installation_candidate: Packages for dosfstools found, but incompatible with the architectures configured>
The next step didn't work either: <wget http://raw.githubusercontent.com/TheExpertNoob/scripts/parts/parts>
Error line: <wget: can't execute 'openssl': No such file or directory>

Is there any way to fix it?

**Comment by TheExpertNoob** [comment]
Yea, this is a REALLY Outdated method. I'll update it as soon as I can. Honestly, I kinda forgot this existed.

dosfstools may take a while to fix, but since openssl isn't installed, that line no longer works since github switched to require SSL. Easy fix, I can mirror that and change a line of code.

I'll start on it this weekend.

**Comment by mstrmnn** [comment]
Thanks a million!

**Comment by TheExpertNoob** [comment]
check to make sure these lines are in your **/etc/opkg/distfeeds.conf** file.
`src/gz openwrt_core http://downloads.openwrt.org/releases/18.06.5/targets/ramips/rt305x/packages
src/gz openwrt_base http://downloads.openwrt.org/releases/18.06.5/packages/mipsel_24kc/base
src/gz openwrt_packages http://downloads.openwrt.org/releases/18.06.5/packages/mipsel_24kc/packages
src/gz openwrt_routing http://downloads.openwrt.org/releases/18.06.5/packages/mipsel_24kc/routing`
